const demotivationalQuotes = [`Does anyone want to be in love so we can split rent?`, 
`When I hear somebody sigh, Life is hard, I am always tempted to ask, Compared to what? – Sydney Harris`, 
`Never regret anything because at one time it was exactly what you wanted.`, 
`Limitations – Until you spread your wings, you’ll have no idea how far you can walk.`, 
`If you put an inspirational quote under your selfie, no one can see your narcissism. – Gandhi`, 
`People often say that motivation doesn’t last. Well, neither does bathing — that’s why we recommend it daily. – Zig Ziglar`, 
`Always borrow money from a pessimist. He won’t expect it back. – Oscar Wilde`, 
`Even a stopped clock is right twice every day. After some years, it can boast of a long series of successes. – Marie von Ebner-Eschenbach`, 
`It will probably get worse.`, 
`We learn from experience that men never learn anything from experience. - George Bernard Shaw`, 
`Live each day like it’s your second to the last. That way you can fall asleep at night. – Jason Love`, 
`Mediocrity-Penguins – Just because we accept you as you are doesn’t mean we’ve abandoned hope you’ll improve.`, 
`I don’t smile in pictures because I’m not a liar.`, 
`Doing nothing is very hard to do… you never know when you’re finished.`, 
`Don’t start believin’.`, 
`Everything is bad and everyone is dumb.`, 
`Your mother’s biggest regret is you.`, 
`I look at the world and see a rainbow of people who all suck in different ways.`, 
`Hard work never killed anybody, but why take a chance?`, 
`Just imagine how terrible it might have been if we’d been at all competent. - Terry Pratchett`, 
`Believe in Yourself – Because the rest of us think you’re an idiot.`, 
`I am so clever that sometimes I don’t understand a single word of what I am saying. – Oscar Wilde`, 
`The worst part of success is trying to find someone who is happy for you. – Bette Midler`, 
`You can’t wait for inspiration. You have to go after it with a club. – Jack London`, 
`If you think you are too small to be effective, you have never been in the dark with a mosquito. – Betty Reese`, 
`Until you spread your wings, you’ll have no idea how far you can walk.`, 
`Success is just failure that hasn't happened yet. - Latrell Sprewell`, 
`You’re born, you work, you die.`, 
`Even if you are on the right track, you’ll get run over if you just sit there. – Will Rogers`, 
`The road to success is always under construction. – Lily Tomlin`, 
`Literally no one cares.`, 
`There are several reasons why I am going to hell.`, 
`Better to remain silent and be thought a fool than to speak out and remove all doubt. – Abraham Lincoln`, 
`much of a good thing can be wonderful. – Mae West`, 
`Don’t be so humble – you are not that great. ― Golda Meir`, 
`Dare to Be Different – Because there’s always room for another annoying non-conformist like you in the enemployment line.`, 
`Killing someone with kindness sounds like a lot of work to me.`, 
`I have better things to do with my time than my job.`, 
`Don’t worry about the world coming to an end today. It is already tomorrow in Australia. – Charles Schulz`, 
`When in doubt, chicken out.`, 
`Whoever sang, ‘Ooh-ooh, child things are gonna get easier’ was laying to that child.`, 
`I used to think I was indecisive, but now I’m not so sure.`, 
`Nobody can stop me but only because I haven’t started yet.`, 
`Why is there so much month left at the end of the money? – John Barrymore`, 
`Every time you tell a dead person to rest in peace, you disturb their rest.`, 
`You can (not) always make a fresh start!`, 
`I’m sorry I didn’t respond to your text. It’s just that I don’t care about your feelings.`, 
`Too much of a good thing can be wonderful. – Mae West`, 
`(You cannot) Be your own best friend!`, 
`Just because we accept you as you are doesn’t mean we’ve abandoned hope you’ll improve.`, 
`I wouldn’t even settle for me, so why would you?`, 
`Work hard and you will (not) get what you deserve!`, 
`The universe doesn’t give a s–t about you.`, 
`Life better be a destination because this journey sucks.`, 
`Every bad thing that happens today is a direct result of choosing to get out of bed.`, 
`Think of how stupid the average person is, and realize half of them are stupider than that. – George Carlin`, 
`Hope is the first step on the road to disappointment. - Cassern S. Goto`, 
`I love you but not as much as I love Netflix`, 
`I don’t want to do things. Things suck.`, 
`This too shall pass and come back worse.`, 
`You’re the human equivalent of a typo.`, 
`Leadership is the art of getting someone else to do something you want done because he wants to do it. – Dwight D. Eisenhower`, 
`Dream Big, Set Goals. Write goals on a nice paper and never look at them again.`, 
`Happiness is just sadness that hasn’t happened yet.`, 
`Going outside is highly overrated. – Ernest Cline`, 
`It’s a beautiful day to shut up.`, 
`Ambition – The journey of a thousand miles sometimes ends very, very, very badly.`, 
`A diamond is merely a lump of coal that did well under pressure. – Unknown`, 
`Try not to talk so much, you’ll sound far less stupid that way. – Brandon Sanderson`, 
`I cannot afford to waste my time making money. – Louis Agassiz`, 
`Always believe that something wonderful will probably never happen.`, 
`When life gives you lemons, squirt someone in the eye. – Cathy Guisewite`, 
`Bad luck = right time, wrong place.`, 
`Always remember you’re someone’s reason to smile because you’re a joke.`, 
`CONSULTING: If you’re not a part of the solution, there’s good money to be made in prolonging the problem.`, 
`When the going gets tough, the tough gets tougher.`, 
`No one gives a s–t about your diet. Just shut up, eat your lettuce and be sad.`, 
`It took me fifteen years to discover I had no talent for writing, but I couldn’t give it up because by then I was too famous. – Robert Benchley`, 
`Humans are 85% water and 15% of idiot meat.`, 
`Today is the first day of the rest of your life. But so was yesterday, and look how that turned out.`, 
`Some people are born losers, others have to learn the hard way.`, 
`Oh, you hate your job? Why didn’t you say so? There’s a support group for that. It’s called EVERYBODY, and they meet at the bar. – Drew Carey`, 
`Is today over yet?`, 
`If at first you don’t succeed, then skydiving definitely isn’t for you. – Steven Wright`, 
`You’re only as good as your last f–k-up.`, 
`Everyone’s entitled to their very stupid opinion.`, 
`Interns – The experience we’re giving you is invaluable. That’s why we’re not paying you anything.`, 
`Never go to bed mad. Stay up and fight. – Phyllis Diller`, 
`We’re doomed.`, 
`Life is what happens when you’re busy reading inspirational quotes.`, 
`Every dead body on Mt. Everest was once a highly motivated person, so… maybe calm down.`, 
`Dream is the only way for you to escape the miserable reality of your life.`, 
`Reach for the stars! Follow your dreams! Live with your parents!`, 
`Do not take life too seriously. You will never get out of it alive. - Elbert Hubbard`, 
`I’d encourage most people to be themselves. For you, that’s cearly the wrong strategy.`, 
`Quitters never win, and winners never quit talking about how they won.`, 
`The only reason some people get lost in thought is that it’s an unfamiliar territory. – Paul Fix`, 
`I thought about losing weight once, but I don’t like losing.`, 
`Friendship is like peeing on yourself: everyone can see it, but only you get the warm feeling that it brings. – Robert Bloch`, 
`School for 12 years, college for 4 years and work until I die. Great!`, 
`Clothes make the man. Naked people have little or no influence in society. – Mark Twain`, 
`A day without sunshine is like, you know, night. – Steve Martin`, 
`The question isn’t who is going to let me, it’s who is going to stop me. – Ayn Rand`, 
`There’s only one you, and that’s a good thing.`, 
`If your brains were dynamite there wouldn’t be enough to blow your hat off – Kurt Vonnegut`, 
`The only thing that has to be finished by next Tuesday is next Monday. – Jennifer Yane`, 
`You can (not) be anything you want to be!`, 
`Don’t cry because it’s over. Smile because if you don’t, everyone will ask you what’s wrong.`, 
`Your dumb ass knew better and your dumb ass still did it.`, 
`You can be stupid or you can be loud. Please don’t be both.`, 
`It’s all downhill from here.`, 
`Help others and you will (not) reap the rewards!`, 
`It’s too early to be alive.`, 
`It is what it is. And it’s not good.`, 
`They say money talks. But, all mine says is goodbye.`, 
`Hard work pays off eventually, but laziness pays off now.`, 
`Welcome to adulthood. I hope you like Ibuprofen.`, 
`You’re naturally funny because your life is a joke.`, 
`It’s a beautiful day to leave me alone.`, 
`You are a background character in a much more interesting person’s story.`, 
`Life is mostly just learning how to lose.`, 
`I’m not lazy. I’m just highly motivated to do nothing.`, 
`When life knocks you down, stay there and take a nap.`, 
`Life is only logical, and to think it’s a gift is depressing.`, 
`Hey, train wreck, this isn’t your station.`, 
`People who say they’ll give 110% don’t understand how percentages work.`, 
`Eagles may soar, but weasels don't get sucked into jet engines. - John Benfield`, 
`Be happy  –  it drives people crazy. – Unknown`, 
`If I’ve ever offended you I’m sorry that you’re a little bi*ch.`, 
`Today I want you to be the best ‘you’ that you can possibly be, which isn’t asking for much.`, 
`Those who doubt your ability probably have a valid reason.`, 
`Mo’ money, no problems.`, 
`Please shut up about your workout.`, 
`If you never try anything new, you’ll miss out on many of life’s great disappointments`, 
`I do marathons…on Netflix.`, 
`Expectations – Refuse to accept anything but the very best and you are never going to last around here.`, 
`I'm sure the universe is full of intelligent life. It's just been too intelligent to come here. - Arthur C. Clarke`, 
`Try & try until you cannot succeed.`, 
`You don’t have haters. No one knows who you are.`, 
`Be the piece of s–t you want to be, not the piece of s–t everyone thinks you are.`, 
`He who laughs last didn’t get the joke. - Charles de Gaulle`, 
`Well-behaved women seldom make history. – Laurel Thatcher Ulrich`, 
`Getting fit is all about mind over matter. I don’t mind, so it doesn’t matter.`, 
`The only way to save the planet is to stop making new people.`, 
`Procrastinate now. Don’t put it off.`, 
`If the world didn’t suck we’d all fly into space. – Unknown`, 
`If everything seems to be going well, you have obviously overlooked something. – Steven Wright`, 
`Date someone who is too good for you and pray they never find out.`, 
`The meaning of life is to find your gift. So good luck with that.`, 
`It’s not just Monday. Your whole life sucks.`, 
`If at first you don’t succeed. Give up and try something else.`, 
`Love conquers all, except for herpes.`, 
`The reward for good work is more work. – Francesca Elisia`, 
`If you’re happy and you know it no one cares.`, 
`If f–g up is power, I should be the Hulk by now. – Richard Kadrey`, 
`It’s never too late to go back to bed.`, 
`There’s no limit to what you can be if you lie to yourself.`, 
`Whenever I feel the need to exercise I lie down until it goes away.`, 
`You did not wake up like that.`, 
`Eat healthy, stay fit, die anyway.`, 
`Some are born great, some achieve greatness, and some wind up like you.`, 
`I would break up with myself if I could.`, 
`I love mankind... it's people I can't stand! - Charles M. Schulz`, 
`Women who seek to be equal with men lack ambition. – Marilyn Monroe`, 
`I always wanted to be somebody, but now I realise I should have been more specific. – Lily Tomlin`, 
`Get lost in nature and you will quite possibly die.`, 
`There is no problem so big you can’t run away from it.`, 
`The worst things in your life probably haven’t happened to you yet.`, 
`You’re too old to be this stupid.`, 
`People say nothing is impossible, but I do nothing every day. – Winnie the Pooh`, 
`Due to recent cutbacks, the light at the end of the tunnel has been turned off.`, 
`Just because you’re paranoid, doesn’t mean they’re not after you.`, 
`There are no stupid questions, but there are a LOT of inquisitive idiots. – Justin Sewell`, 
`Be the Bridge – that way we can walk all over you on your way to better places.`, 
`Every morning wake up and scream your dreams into a garbage can where they belong.`, 
`Think like a proton. Always positive. – Unknown`, 
`You’re only as deep as your most recent inspirational quote.`, 
`Practice makes perfect, but if nobody’s perfect, why practice?`, 
`Mistakes – it could be that the purpose of your life is only to serve as a warning to others.`, 
`The secret of my success? I make a list of things not to do, and then I check them off as I don’t do them.`, 
`The brain is a wonderful organ; it starts working the moment you get up in the morning and does not stop until you get into the office. – Robert Frost`, 
`Every day is a new chance for you to screw up again.`, 
`You really can (not)!`, 
`Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead`, 
`It will (not) all work out in the end!`, 
`Accept that you’re just a product, not a gift.`, 
`Life hack: you can’t do anything wrong if you don’t do anything at all.`, 
`Meetings – None of us is as dumb as all of us. `, 
`The first step towards failure is trying.`, 
`The light at the end of the tunnel has been turned off due to budget cuts. - Steven Wright`, 
`If at first you don't succeed, try, try again. Then quit. No use being a damn fool about it. - W.C. Fields`, 
`By replacing your morning coffee with green tea, you can lose up to 87% of what little joy you still have left in your life.`, 
`Life is hard, but it’s even harder if you’re stupid.`, 
`Hey, can you shut up? Asking for a friend.`, 
`Don’t let the bastards cheer you up.`, 
`Every group needs its twat, and if you’re in a group of people and there isn’t a twat, then it’s you. – Angus Watson`, 
`Nothing is impossible, the word itself says I’m possible! – Audrey Hepburn`, 
`Progress – Just made you irrelevant.`, 
`Step out of your comfort zone and then step back in immediately and appreciate how nice and comfy it is.`, 
`Trying is the first step toward failure. – Homer Simpson`, 
`I didn’t fail the test. I just found 100 ways to do it wrong. – Benjamin Franklin`, 
`The best things in life are actually really expensive.`, 
`I am an early bird and a night owl… so I am wise and I have worms. – Michael Scott`, 
`Even if you are one in a million, there are still 7,700 others like you!`, 
`Monday hates you too.`, 
`Eat like no one is going to see you naked.`, 
`Life is pain. Anyone who says otherwise is selling something. – William Goldman`, 
`According to Astronomy, when you wish upon a star, you’re actually a few million years too late. That star is dead. Just like your dreams.`, 
`Will it be easy? Nope. Worth it? Absolutely not!`, 
`The elevator to success is out of order. You’ll have to use the stairs, one step at a time. – Joe Girard`, 
`Not everything is a lesson. Sometimes you just fail. – Dwight Schrute`, 
`Failure is always an option.`, 
`Go ahead let your dreams punch you in the face.`, 
`Age is of no importance unless you’re a cheese. – Billie Burke`, 
`You thank God daily, but have you ever once heard a ‘You’re welcome’?`, 
`Can stop, will stop.`, 
`No one in charge of your happiness but you. But should you really be put in charge of anything?`, 
`The road to success is dotted with many tempting parking spaces. – Will Rogers`, 
`It’s true hard work never killed anybody, but I figure, why take the chance? – Ronald Reagan`, 
`There is no sunrise so beautiful that it is worth waking me up to see it. – Mindy Kaling`, 
`I’ll get coffee with you but only because I love coffee.`, 
`If you let your head get too big, it’ll break your neck. – Elvis Presley`, 
`Dream big… But from bed.`, 
`When work feels overwhelming, remember that you’re going to die.`, 
`My five-year plan is to watch everything on Netflix.`, 
`TEAMWORK: A few harmless flakes working together can unleash an avalanche of destruction. - Justin Sewell`, 
`Life’s a b**ch, and then you die.`, 
`Whoever said money can’t buy happiness didn’t know where to shop. – Gertrude Stein`, 
`Drop it like it’s your hopes and dreams.`, 
`I’m sure the universe is full of intelligent life. It’s just been too intelligent to come here. – Arthur C. Clarke`, 
`Started from the bottom and still at the bottom.`, 
`I always arrive late at the office, but I make up for it by leaving early – Charles Lamb`, 
`I am free of all prejudice. I hate everyone equally. - W.C. Fields`, 
`Get to work, you aren’t being paid to believe in the power of your dreams.`, 
`Nothing says ‘you’re a loser’ more than owning a motivational poster about being a winner.`, 
`The more you weigh, the harder you are to kidnap. Stay safe. Eat cake.`, 
`The only thing worse than mornings are morning people.`, 
`Honest criticism is hard to take, particularly from a relative, a friend, an acquaintance, or a stranger. – Franklin P. Jones`, 
`By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day. – Robert Frost`, 
`Dreams are like rainbows. Only idiots chase them.`, 
`Every tattoo is temporary because we’re all slowly dying.`, 
`Eat that cake because it’s somebody’s birthday somewhere.`, 
`Get ready for more of the same.`, 
`The key to happiness is low expectations. Lower. Nope, even lower. There you go.`, 
`Dream – the first thing people abandon when they understand how the world works.`, 
`Flattery – if you want to get to the top, prepare to kiss a lot of the bottom.`, 
`ose who doubt your ability probably have a valid reason.`, 
`Honesty is the best policy to pretend you believe in.`, 
`Everything happens for a reason. Sometimes the reason is that you’re stupid and make bad decisions. – Marion G. Harmon`, 
`It takes 37 muscles to frown but it only takes zero muscles to shut the f–k up.`, 
`There’s always someone on Youtube that can do it better than you.`, 
`I’d rather be sleeping.`, 
`A thousand-mile journey starts with one step. Then again, so does falling in ditch and breaking your neck.`, 
`If you never believe in yourself, you’ll never let yourself down.`, 
`There is always room in your life to f–k more s-t up. Always.`, 
`Given a choice, you will always choose wrong.`, 
`Everyone has a purpose in life. Perhaps yours is watching television – David Letterman`, 
`I love deadlines. I like the whooshing sound they make as they fly by. – Douglas Adams`, 
`I have a simple philosophy: Fill what is empty. Empty what is full. Scratch where it itches. – Alice Roosevelt Longworth`, 
`Complaining is my hobby.`, 
`Never put off until tomorrow what you can do the day after tomorrow. – Mark Twain`, 
`Don’t rest until you’ve complained about everything.`, 
`Go ahead and take risks – it gives the rest of us something to laugh at.`, 
`The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it. – Terry Pratchett`, 
`Bad decisions make good stories. – Ellis Vidler`, 
`Never miss a good chance to shut up.`, 
`Try hard and don’t worry if you fail because everyone expected that.`, 
`Life is like a sewer – what you get out of it depends on what you put into it. – Tom Lehrer`, 
`If your coffee order is more than four words, you are part of the problem.`]



let messageIndex;
try {
    messageIndex = JSON.parse(new URLSearchParams(location.search).get('index'));
} catch (e) {}

// simplify the displayed URL in the address bar

let deMoElement = document.querySelector('.de-mo-quote');
const deMoQuoteIndex = messageIndex ?? Math.floor(Math.random() * demotivationalQuotes.length)
deMoElement.textContent = demotivationalQuotes[deMoQuoteIndex]