const demotivationalQuotes = [`Your life only goes up so you can fall from a new height.`, 
`Your life can’t fall apart if you never had it together.`, 
`Your dumb ass knew better and your dumb ass still did it.`, 
`Your dog only loves you because you have food.`, 
`You’re too old to be this stupid.`, 
`You’re the human equivalent of a typo.`, 
`You’re only as good as your last f–k-up.`, 
`You’re only as deep as your most recent inspirational quote.`, 
`You’re naturally funny because your life is a joke.`, 
`You’re about to get even fatter.`, 
`You tried your best and failed miserably. The lesson is, never try. – Homer Simpson`, 
`You put the ace in disgrace.`, 
`You only die once.`, 
`You miss 100% of the shots you do take also.`, 
`You have to make the good out of the bad because that is all you have got to make it out of. - Robert Penn Warren`, 
`You don’t have haters. No one knows who you are.`, 
`You did not wake up like that.`, 
`You can have results or excuses. Excuses it is.`, 
`You can be stupid or you can be loud. Please don’t be both.`, 
`You can be replaced.`, 
`You are a background character in a much more interesting person’s story.`, 
`Work hard, complain harder.`, 
`Will it be easy? Nope. Worth it? Absolutely not!`, 
`Why stand out when you’re born to blend in?`, 
`Why is there so much month left at the end of the money? – John Barrymore`, 
`Whoever sang, ‘Ooh-ooh, child things are gonna get easier’ was laying to that child.`, 
`Whoever said money can’t buy happiness didn’t know where to shop. – Gertrude Stein`, 
`When you think you’re screwed, remember we’re all on a big, wet ball floating in the dark.`, 
`When work feels overwhelming, remember that you’re going to die.`, 
`When we talk to God, we’re praying. When God talks to us, we’re schizophrenic. - Jane Wagner`, 
`When the going gets tough, the tough gets tougher.`, 
`When someone says you’re one in a million, what they’re really saying is that there’s over 7000 people just like you.`, 
`When life knocks you down, stay there and take a nap.`, 
`When in doubt, chicken out.`, 
`When a man tells you that he got rich through hard work, ask him: Whose?`, 
`What a day!! Nothing happened and I was tired.`, 
`Welcome to adulthood. I hope you like Ibuprofen.`, 
`We’re doomed.`, 
`We learn from experience that men never learn anything from experience. - George Bernard Shaw`, 
`Until you spread your wings, you’ll have no idea how far you can walk.`, 
`Two wrongs don’t make a right, but they make a good excuse. – Thomas Stephen Szasz`, 
`Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein`, 
`Turn that smile upside down.`, 
`Trying is the first step toward failure. - Homer Simpson`, 
`Try not to talk so much, you’ll sound far less stupid that way. – Brandon Sanderson`, 
`Try hard and don’t worry if you fail because everyone expected that.`, 
`True love is when two people lower their standards just the right amount.`, 
`Today will be a day like every other day.`, 
`Today is the first day of the rest of your life. But so was yesterday, and look how that turned out.`, 
`Those who doubt your ability probably have a valid reason.`, 
`This too shall pass and come back worse.`, 
`Think of how stupid the average person is, and realize half of them are stupider than that. – George Carlin`, 
`They say money talks. But, all mine says is goodbye.`, 
`There’s someone for everyone, except for you.`, 
`There’s no U in Happy.`, 
`There’s no limit to what you can be if you lie to yourself.`, 
`There’s always time to complain.`, 
`There’s always someone on Youtube that can do it better than you.`, 
`There is no sunrise so beautiful that it is worth waking me up to see it. – Mindy Kaling`, 
`There is no problem so big you can’t run away from it.`, 
`There is always room in your life to f–k more shit up. Always.`, 
`There are two types of people in the world and I hate both of them.`, 
`There are plenty of fish in the sea, none of them want to date you either.`, 
`There are no stupid questions, but there are a LOT of inquisitive idiots.`, 
`The worst things in your life probably haven’t happened to you yet.`, 
`The worst part of success is trying to find someone who is happy for you. - Bette Midler`, 
`The universe doesn’t give a s–t about you.`, 
`The two most common elements in the universe are hydrogen and stupidity. – Harlan Ellison`, 
`The story so far: In the beginning, the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move. - Douglas Adams`, 
`The story so far: In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move. - Douglas Adams`, 
`The road to success is always under construction. – Lily Tomlin`, 
`The reward for good work is more work. – Francesca Elisia`, 
`The only way to save the planet is to stop making new people.`, 
`The only thing worse than mornings are morning people.`, 
`The only thing that has to be finished by next Tuesday is next Monday. – Jennifer Yane`, 
`The only thing all of your failures have in common is you.`, 
`The only reason some people get lost in thought is that it’s an unfamiliar territory. – Paul Fix`, 
`The more you weigh, the harder you are to kidnap. Stay safe. Eat cake.`, 
`The meaning of life is to find your gift. So good luck with that.`, 
`The light at the end of the tunnel has been turned off due to budget cuts. - Steven Wright`, 
`The key to happiness is low expectations. Lower. Nope, even lower. There you go.`, 
`The first step toward failure is trying.`, 
`The elevator to success is out of order. You’ll have to use the stairs, one step at a time. – Joe Girard`, 
`The capacity for friendship is God's way of apologizing for our families. - Jay McInerney`, 
`The brain is a wonderful organ; it starts working the moment you get up in the morning and does not stop until you get into the office. – Robert Frost`, 
`The best way to lose weight is to only eat inspirational quotes.`, 
`The best things in life are actually really expensive. - Unknown`, 
`TEAMWORK: A few harmless flakes working together can unleash an avalanche of destruction. - Justin Sewell`, 
`Talking is cool, but have you ever tried shutting the f–k up instead?`, 
`Success is just failure that hasn't happened yet. - Latrell Sprewell`, 
`Started from the bottom and still at the bottom.`, 
`Start each day with a goal so you have something to f–k up.`, 
`Some people are born losers, others have to learn the hard way.`, 
`Shutting the f–k up is gluten-free. Add that to your diet.`, 
`Reach for the stars! Follow your dreams! Live with your parents!`, 
`Raise your hand if you have had quite enough unsolicited advice about what should be done with any lemons that life may or may not give you.`, 
`Quitters never win, and winners never quit talking about how they won.`, 
`Prove them wrong. Show them how much worse than what they think you actually are.`, 
`Practice makes perfect, but if nobody’s perfect, why practice?`, 
`Please shut up about your workout.`, 
`Perseverance is the ability to think you’re not an idiot despite the overwhelming evidence to the contrary.`, 
`People who say they’ll give 110% don’t understand how percentages work.`, 
`People are really great as long as you don’t get to know them.`, 
`Others can’t use you if you’re useless.`, 
`Oh, you hate your job? Why didn’t you say so? There’s a support group for that. It’s called EVERYBODY, and they meet at the bar. – Drew Carey`, 
`Nothing says ‘you’re a loser’ more than owning a motivational poster about being a winner.`, 
`Not everything is a lesson. Sometimes you just fail. - Dwight Schrute`, 
`None of your emails are finding me well.`, 
`Nobody gives a s–t about what you ate for lunch.`, 
`No one in charge of your happiness but you. But should you really be put in charge of anything?`, 
`No one gives a s–t about your diet. Just shut up, eat your lettuce and be sad.`, 
`Ninety-five percent of conversations are an unbelievable waste of time.`, 
`Never. Give up.`, 
`Never worry what other people think of you because no one ever thinks of you. ― Brian K. Vaughan,`, 
`Never underestimate the power of stupid people in large groups. - George Carlin`, 
`Never miss a good chance to shut up.`, 
`Never go to bed mad. Stay up and fight. – Phyllis Diller`, 
`My five-year plan is to watch everything on Netflix.`, 
`Multitasking – the art of doing twice as much as you should half as well as you could.`, 
`Most people are idiots. There’s nothing worse than idiots who tell you their opinions. – Richard Kadrey`, 
`Monday hates you too.`, 
`Mo’ money, no problems.`, 
`Meetings – None of us is as dumb as all of us. `, 
`Mediocrity in your goals is the key to never falling short of your expectations.`, 
`Literally no one cares.`, 
`Light travels faster than sound. This is why some people appear bright until you hear them speak. - Alan Dundes`, 
`Life’s a bitch, and then you die.`, 
`Life is what happens when you’re busy reading inspirational quotes.`, 
`Life is pain. Anyone who says otherwise is selling something. – William Goldman`, 
`Life is mostly just learning how to lose.`, 
`Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein`, 
`Life is hard, but it’s even harder if you’re stupid.`, 
`Life is a series of things we would rather not to. – Joe Abercrombie`, 
`Life is 10% what happens to you, and 90% how much money you have.`, 
`Life hack: you can’t do anything wrong if you don’t do anything at all.`, 
`Life better be a destination because this journey sucks.`, 
`Killing someone with kindness sounds like a lot of work to me.`, 
`Keep panicking.`, 
`Just imagine how terrible it might have been if we’d been at all competent. - Terry Pratchett`, 
`Just because you’re paranoid, doesn’t mean they’re not after you.`, 
`Just because you are unique doesn't mean you are useful.`, 
`Just because we accept you as you are doesn’t mean we’ve abandoned hope you’ll improve.`, 
`It’s true hard work never killed anybody, but I figure, why take the chance? – Ronald Reagan`, 
`It’s too early to be alive.`, 
`It’s only when you look at an ant through a magnifying glass on a sunny day that you realize how often they burst into flames. - Harry Hill`, 
`It’s not just Monday. Your whole life sucks.`, 
`It’s never too late to go back to bed.`, 
`It’s never too late to fail.`, 
`It’s all downhill from here.`, 
`It’s a beautiful day to shut up.`, 
`It’s a beautiful day to leave me alone.`, 
`It will probably get worse.`, 
`It takes 37 muscles to frown but it only takes zero muscles to shut the f–k up.`, 
`It is what it is. And it’s not good.`, 
`It could be that your purpose in life is to serve as a warning to others. - Ashleigh Brilliant`, 
`Is today over yet?`, 
`In the beginning, love is mostly about lying to each other. It’s like that in the end, too. ― Brian K. Vaughan`, 
`If your phone battery lasts all day, it’s because no one likes you.`, 
`If your coffee order is more than four words, you are part of the problem.`, 
`If your brains were dynamite there wouldn’t be enough to blow your hat off – Kurt Vonnegut`, 
`If you’re happy and you know it no one cares.`, 
`If you want to make God laugh, tell him about your plans. – Woody Allen`, 
`If you want to know what God thinks of money, just look at the people he gave it to. - Dorothy Parker`, 
`If you put an inspirational quote under your selfie, no one can see your narcissism. – Gandhi`, 
`If you never try anything new, you’ll miss out on many of life’s great disappointments`, 
`If you never believe in yourself, you’ll never let yourself down.`, 
`If the world didn’t suck we’d all fly into space.`, 
`If life doesn’t break you today, don’t worry. It will try again tomorrow.`, 
`If I’ve ever offended you I’m sorry that you’re a little bi*ch.`, 
`If f–g up is power, I should be the Hulk by now. – Richard Kadrey`, 
`If everything seems to be going well, you have obviously overlooked something. – Steven Wright`, 
`If at first you don't succeed, try, try again. Then quit. No use being a damn fool about it. - W.C. Fields`, 
`Idiocy – never underestimate the power of stupid people in large groups.`, 
`I’ve developed a new philosophy. I only dread one day at a time. - Charlie Brown/Charles M. Schulz`, 
`I’m sure the universe is full of intelligent life. It’s just been too intelligent to come here. – Arthur C. Clarke`, 
`I’m sick of following my dreams. I’m just going to ask them where they’re going and hook up with them later. – Mitch Hedberg`, 
`I’d rather be sleeping.`, 
`I'm sure the universe is full of intelligent life. It's just been too intelligent to come here. - Arthur C. Clarke`, 
`I wouldn’t even settle for me, so why would you?`, 
`I would break up with myself if I could.`, 
`I thought about losing weight once, but I don’t like losing.`, 
`I love mankind... it's people I can't stand! - Charles M. Schulz`, 
`I love hating things.`, 
`I love deadlines. I like the whooshing sound they make as they fly by. – Douglas Adams`, 
`I have learned from my mistakes, and I am sure I can repeat them exactly. – Peter Cook`, 
`I have better things to do with my time than my job.`, 
`I don’t want to do things. Things suck.`, 
`I don’t smile in pictures because I’m not a liar.`, 
`I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal. - Jane Austen`, 
`I can but I literally refuse to even.`, 
`I am free of all prejudice. I hate everyone equally. - W.C. Fields`, 
`I always arrive late at the office, but I make up for it by leaving early – Charles Lamb`, 
`Humans are 85% water and 15% of idiot meat.`, 
`Hope is the first step on the road to disappointment. - Cassern S. Goto`, 
`Honesty is the best policy to pretend you believe in.`, 
`Hey, train wreck, this isn’t your station.`, 
`Hey, can you shut up? Asking for a friend.`, 
`He who laughs last didn’t get the joke. - Charles de Gaulle`, 
`He loved asses so much he became one.`, 
`Have no fear of perfection. You’ll never reach it. – Salvador Dali`, 
`Have a mediocre weekend! You’ve earned it!`, 
`Have a great day! Or don’t! No one cares!`, 
`Hard work pays off eventually, but laziness pays off now.`, 
`Happiness is just a lack of information.`, 
`Going outside is highly overrated. – Ernest Cline`, 
`Go to heaven for the climate and hell for the company. – Benjamin Franklin Wade`, 
`Go ahead let your dreams punch you in the face.`, 
`Go ahead and take risks – it gives the rest of us something to laugh at.`, 
`Give yourself an A for Average.`, 
`Get to work, you aren’t being paid to believe in the power of your dreams.`, 
`Get ready for more of the same.`, 
`Get lost in nature and you will quite possibly die.`, 
`Find the one thing you love and shut up about it.`, 
`Fate is like a strange, unpopular restaurant filled with odd little waiters who bring you things you never asked for and don't always like. - Lemony Snicket`, 
`Failure is always an option.`, 
`Everything is bad and everyone is dumb.`, 
`Everything happens for a reason. Sometimes the reason is that you’re stupid and make bad decisions. – Marion G. Harmon`, 
`Everyone’s entitled to their very stupid opinion.`, 
`Everyone has a purpose in life. Perhaps yours is watching television – David Letterman`, 
`Everybody sucks at something.`, 
`Every tattoo is temporary because we’re all slowly dying.`, 
`Every morning wake up and scream your dreams into a garbage can where they belong.`, 
`Every group needs its twat, and if you’re in a group of people and there isn’t a twat, then it’s you. – Angus Watson`, 
`Every dead body on Mt. Everest was once a highly motivated person, so… maybe calm down.`, 
`Every day is Friday when you’re unemployed.`, 
`Every day is a new chance for you to screw up again.`, 
`Every bad thing that happens today is a direct result of choosing to get out of bed.`, 
`Eat that cake because it’s somebody’s birthday somewhere.`, 
`Eat like no one is going to see you naked.`, 
`Eat healthy, stay fit, die anyway.`, 
`Eagles may soar, but weasels don't get sucked into jet engines. - John Benfield`, 
`Due to recent cutbacks, the light at the end of the tunnel has been turned off.`, 
`Drop it like it’s your hopes and dreams.`, 
`Dreams are like rainbows. Only idiots chase them.`, 
`Dream big… But from bed.`, 
`Dream big. Then settle.`, 
`Dream Big, Set Goals. Write goals on a nice paper and never look at them again.`, 
`Dream – the first thing people abandon when they understand how the world works.`, 
`Don’t start believin’.`, 
`Don’t rest until you’ve complained about everything.`, 
`Don’t let the bastards cheer you up.`, 
`Don’t cry because it’s over. Smile because if you don’t, everyone will ask you what’s wrong.`, 
`Don’t be so humble – you are not that great. ― Golda Meir`, 
`Doing nothing is very hard to do… you never know when you’re finished.`, 
`Does anyone want to be in love so we can split rent?`, 
`Do not take life too seriously. You will never get out of it alive. - Elbert Hubbard`, 
`Date someone who is too good for you and pray they never find out.`, 
`Complaining is my hobby.`, 
`Coffee doesn’t love you back.`, 
`Clothes make the man. Naked people have little or no influence in society. – Mark Twain`, 
`Challenging yourself...is a good way to fail. - Dom Mazzetti`, 
`Carpe Nothing.`, 
`Can stop, will stop.`, 
`By replacing your morning coffee with green tea, you can lose up to 87% of what little joy you still have left in your life.`, 
`Boldly going nowhere.`, 
`Better to remain silent and be thought a fool than to speak out and remove all doubt. – Abraham Lincoln`, 
`Before you judge someone else, try to keep in mind that you’re probably a piece of s–t too.`, 
`Be yourself. No one else wants to be you.`, 
`Be yourself, everyone else is already a twat.`, 
`Be the piece of s–t you want to be, not the piece of s–t everyone thinks you are.`, 
`Be the bridge – that way we can walk all over you on your way to better places.`, 
`Ambition is a poor excuse for not having sense enough to be lazy. – Charlie McCarthy`, 
`Always remember you’re someone’s reason to smile because you’re a joke.`, 
`Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead`, 
`Always borrow money from a pessimist. He won’t expect it back. – Oscar Wilde`, 
`Always believe that something wonderful will probably never happen.`, 
`According to Astronomy, when you wish upon a star, you’re actually a few million years too late. That star is dead. Just like your dreams.`, 
`A thousand-mile journey starts with one step. Then again, so does falling in a ditch and breaking your neck.`, 
`A day without sunshine is like, you know, night.`]



let deMoElement = document.querySelector('.de-mo-quote');
deMoElement.textContent = demotivationalQuotes [70];